# @formatter:off
fhir-bridge:
  fhir:
    endpoints:
      DocumentReference: false
#  minio:
#    url: http://localhost:9000
#    access-key:
#    secret-key:
#    bucket-name:

# CORS Properties
  cors:
    allow-credentials: false
    allowed-headers: '*'
    allowed-methods: '*'
    allowed-origins: '*'
# Debug Properties
  debug:
    #enabled: false
    enabled: true
    #mapping-output-directory: ${java.io.tmpdir}/mappings
    mapping-output-directory: src/main/resources/mappings
# EHRbase Properties
  ehrbase:
    base-url: http://localhost:8080/ehrbase/
    security:
      type: basic
      user:
        name: myuser
        password: myPassword432
        admin-name: myadmin
        admin-password: mySuperAwesomePassword123
#      oauth2:
#        token-url:
#        client-id:
#        client-secret:
    template:
      prefix: classpath:/opt/
      force-update: false
# FHIR Properties
#  fhir:
#    jpa:
#      allow-external-references:
#      allow-inline-match-url-references:
#      auto-create-placeholder-references:
#      populate-identifier-in-auto-created-placeholder-references:
#    validation:
#      any-extensions-allowed:
#      error-for-unknown-profiles:
#      failed-on-severity:
#      optional-identifier:
#      terminology:
#        mode:
#        server-base-url:
# HTTP Client Properties
#  http-client:
#    ssl:
#      enabled:
#      key-password:
#      key-store:
#      key-store-password:
#      key-store-type:
#      trust-store:
#      trust-store-password:
#      trust-store-type:
# Security Properties
  security:
    authentication-type: none
#    basic:
#      username:
#      password:
#    oauth2:
#      jwk-set-uri:
#      jws-algorithm: RS256

################################################################################
# Spring Properties                                                            #
################################################################################

spring:
  application:
    name: FHIR Bridge
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
# Batch Properties
  batch:
    job:
      enabled: false
# JPA Properties
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.search.enabled: true
      hibernate.search.backend.type: lucene
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: ${java.io.tmpdir}/fhir-bridge/lucenefiles
      hibernate.search.backend.lucene_version: lucene_current
# Liquibase Properties
  liquibase:
    database-change-log-table: DATABASE_CHANGELOG
    database-change-log-lock-table: DATABASE_CHANGELOG_LOCK
    change-log: classpath:/db/changelog/db.changelog-master.xml
  messages:
    basename: messages/messages
    use-code-as-default-message: true
# Server Properties
server:
  port: 8888
  servlet:
    context-path: /fhir-bridge
# Logging Properties
logging:
  file:
    name: ./logs/fhir-bridge.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
  level:
    ca.uhn.fhir: error
    com.zaxxer.hikari: error
    liquibase: error
    org.apache.camel: error
    org.ehrbase.client: warn
    org.ehrbase.fhirbridge: info
    org.hibernate: error
    org.openehealth.ipf: error
    org.quartz: error
    org.springframework: error
    org.springframework.boot: error
# Management Properties
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
      exposure:
        include: env, health, info, liquibase, logfile, loggers
  metrics:
    export:
      elastic:
        auto-create-index:

################################################################################
# Open eHealth Integration Platform Properties                                 #
################################################################################

ipf:
  # Audit Properties
  atna:
    audit-enabled: false
#    audit-repository-host:
#    audit-repository-port:
#    audit-source-id:
#    audit-value-if-missing:
  # FHIR Properties
  fhir:
    fhir-version: r4

demographics:
  patient:
    url: https://demographics-service.ctr.dev.num-codex.de/fhir/Patient/