version: '3'
services:
  ehrbase:
    image: ehrbaseorg/ehrbase:next
    ports:
      - 8080:8080
    networks:
      - ehrbase-network
    environment:
      DB_URL: jdbc:postgresql://ehrbase-db:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: myuser
      SECURITY_AUTHPASSWORD: myPassword432
      SECURITY_AUTHADMINUSER: myadmin
      SECURITY_AUTHADMINPASSWORD: mySuperAwesomePassword123
      SYSTEM_NAME: local.ehrbase.org
    depends_on:
      - ehrbase-db
    restart: on-failure
  ehrbase-db:
    image: ehrbaseorg/ehrbase-postgres:latest
    ports:
      - 5432:5432
    networks:
      - ehrbase-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
  elasticsearch:
    image: elasticsearch:7.7.0
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - ehrbase-network
  kibana:
    image: kibana:7.7.0
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - ehrbase-network
  logstash:
    image: logstash:7.7.0
    hostname: logstash
    ports:
      - 9600:9600
      - 8089:8089
      - 3001:3001/udp
    volumes:
      - ./logstash:/usr/share/logstash/pipeline/
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - ehrbase-network
networks:
  ehrbase-network: { }
