version: '3'
services:
  ehrbase:
    image: ehrbase/ehrbase:0.23.0 #0.18.2 was the old version used to run 90% of the tests.
    ports:
      - 8080:8080
    networks:
      - ehrbase-network
    environment:
      DB_URL: jdbc:postgresql://ehrbase-db:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: myuser
      SECURITY_AUTHPASSWORD: myPassword432
      SECURITY_AUTHADMINUSER: myadmin
      SECURITY_AUTHADMINPASSWORD: mySuperAwesomePassword123
      SYSTEM_NAME: local.ehrbase.org
      ADMIN_API_ACTIVE: 'true'
      SERVER_DISABLESTRICTVALIDATION: 'true'
    depends_on:
      - ehrbase-db
    restart: on-failure
  ehrbase-db:
    image: ehrbase/ehrbase-postgres:13.4
    ports:
      - 15432:5432
    networks:
      - ehrbase-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data --console-address ":9001"
networks:
  ehrbase-network: { }
